#!/usr/bin/env python3
"""Turn a .ino into a .cpp the desktop test harness can compile.

Swaps the Arduino headers for the stubs in this folder, adds the function
prototypes the Arduino IDE would generate automatically, and renames setup/loop
so the test harness owns main().

Usage:  python3 generate.py            # regenerate both sketches
"""
import pathlib, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

TARGETS = [
    (ROOT / "my-version" / "IRTurretMine.ino", HERE / "sketch.cpp"),
    (ROOT / "IRTurret_FixedFiring.ino",        HERE / "community_sketch.cpp"),
]

ARDUINO_HEADERS = ["#include <Arduino.h>", "#include <Servo.h>", "#include <IRremote.hpp>"]

PROLOGUE = """// GENERATED by tools/generate.py - do not edit. Edit the .ino and regenerate.
#include "stubs.h"
void upMove(int moves);
void downMove(int moves);
void leftMove(int moves);
void rightMove(int moves);
void fire();
void fireAll();
void homeServos();
void addPasscodeDigit(char digit);
void checkPasscode();
"""

def generate(src: pathlib.Path, dst: pathlib.Path) -> None:
    text = src.read_text()
    for header in ARDUINO_HEADERS:
        text = text.replace(header, "")
    prologue = PROLOGUE
    if "CORRECT_PASSCODE" not in text:          # community sketch has no passcode
        prologue = prologue.replace("void addPasscodeDigit(char digit);\n", "")
        prologue = prologue.replace("void checkPasscode();\n", "")
    text = text.replace("void setup() {", "void sketch_setup() {")
    text = text.replace("void loop() {", "void sketch_loop() {")
    dst.write_text(prologue + text)
    print(f"generated {dst.name} from {src.name}")

if __name__ == "__main__":
    for src, dst in TARGETS:
        if not src.exists():
            sys.exit(f"missing {src}")
        generate(src, dst)
